# Generated by Django 4.0.6 on 2023-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenRecorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='VideoChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('chunk_number', models.PositiveIntegerField()),
                ('total_chunks', models.PositiveIntegerField()),
                ('video_chunk', models.FileField(upload_to='video_chunks/')),
            ],
        ),
    ]
